/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_rapids_cudf_Cudf */

#ifndef _Included_ai_rapids_cudf_Cudf
#define _Included_ai_rapids_cudf_Cudf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_rapids_cudf_Cudf
 * Method:    gdfAddGeneric
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_ai_rapids_cudf_Cudf_gdfAddGeneric
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_rapids_cudf_Cudf
 * Method:    gdfAddI32
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_ai_rapids_cudf_Cudf_gdfAddI32
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_rapids_cudf_Cudf
 * Method:    gdfAddI64
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_ai_rapids_cudf_Cudf_gdfAddI64
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_rapids_cudf_Cudf
 * Method:    gdfAddF32
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_ai_rapids_cudf_Cudf_gdfAddF32
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_rapids_cudf_Cudf
 * Method:    gdfAddF64
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_ai_rapids_cudf_Cudf_gdfAddF64
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     ai_rapids_cudf_Cudf
 * Method:    gdfExtractDatetimeYear
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ai_rapids_cudf_Cudf_gdfExtractDatetimeYear
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_rapids_cudf_Cudf
 * Method:    gdfExtractDatetimeMonth
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ai_rapids_cudf_Cudf_gdfExtractDatetimeMonth
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_rapids_cudf_Cudf
 * Method:    gdfExtractDatetimeDay
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ai_rapids_cudf_Cudf_gdfExtractDatetimeDay
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_rapids_cudf_Cudf
 * Method:    gdfExtractDatetimeHour
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ai_rapids_cudf_Cudf_gdfExtractDatetimeHour
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_rapids_cudf_Cudf
 * Method:    gdfExtractDatetimeMinute
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ai_rapids_cudf_Cudf_gdfExtractDatetimeMinute
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_rapids_cudf_Cudf
 * Method:    gdfExtractDatetimeSecond
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ai_rapids_cudf_Cudf_gdfExtractDatetimeSecond
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
