/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_rapids_cudf_Rmm */

#ifndef _Included_ai_rapids_cudf_Rmm
#define _Included_ai_rapids_cudf_Rmm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_rapids_cudf_Rmm
 * Method:    initialize
 * Signature: (IZJ)V
 */
JNIEXPORT void JNICALL Java_ai_rapids_cudf_Rmm_initialize
  (JNIEnv *, jclass, jint, jboolean, jlong);

/*
 * Class:     ai_rapids_cudf_Rmm
 * Method:    alloc
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_ai_rapids_cudf_Rmm_alloc
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ai_rapids_cudf_Rmm
 * Method:    free
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_ai_rapids_cudf_Rmm_free
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
