/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_rapids_cudf_CudfTable */

#ifndef _Included_ai_rapids_cudf_CudfTable
#define _Included_ai_rapids_cudf_CudfTable
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_rapids_cudf_CudfTable
 * Method:    createCudfTable
 * Signature: ([J)J
 */
JNIEXPORT jlong JNICALL Java_ai_rapids_cudf_CudfTable_createCudfTable
  (JNIEnv *, jclass, jlongArray);

/*
 * Class:     ai_rapids_cudf_CudfTable
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_rapids_cudf_CudfTable_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ai_rapids_cudf_CudfTable
 * Method:    gdfOrderBy
 * Signature: (J[J[ZJZ)V
 */
JNIEXPORT void JNICALL Java_ai_rapids_cudf_CudfTable_gdfOrderBy
  (JNIEnv *, jclass, jlong, jlongArray, jbooleanArray, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
