/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_rapids_bindings_cuda_Cuda */

#ifndef _Included_ai_rapids_bindings_cuda_Cuda
#define _Included_ai_rapids_bindings_cuda_Cuda
#ifdef __cplusplus
extern "C" {
#endif
#undef ai_rapids_bindings_cuda_Cuda_cudaCpuDeviceId
#define ai_rapids_bindings_cuda_Cuda_cudaCpuDeviceId -1L
/*
 * Class:     ai_rapids_bindings_cuda_Cuda
 * Method:    memGetInfo
 * Signature: ()Lai/rapids/bindings/cuda/CudaMemInfo;
 */
JNIEXPORT jobject JNICALL Java_ai_rapids_bindings_cuda_Cuda_memGetInfo
  (JNIEnv *, jclass);

/*
 * Class:     ai_rapids_bindings_cuda_Cuda
 * Method:    memcpy
 * Signature: (JJJI)V
 */
JNIEXPORT void JNICALL Java_ai_rapids_bindings_cuda_Cuda_memcpy
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
