/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_rapids_cudf_Cuda */

#ifndef _Included_ai_rapids_cudf_Cuda
#define _Included_ai_rapids_cudf_Cuda
#ifdef __cplusplus
extern "C" {
#endif
#undef ai_rapids_cudf_Cuda_CPU_DEVICE_ID
#define ai_rapids_cudf_Cuda_CPU_DEVICE_ID -1L
/*
 * Class:     ai_rapids_cudf_Cuda
 * Method:    memGetInfo
 * Signature: ()Lai/rapids/cudf/CudaMemInfo;
 */
JNIEXPORT jobject JNICALL Java_ai_rapids_cudf_Cuda_memGetInfo
  (JNIEnv *, jclass);

/*
 * Class:     ai_rapids_cudf_Cuda
 * Method:    memcpy
 * Signature: (JJJI)V
 */
JNIEXPORT void JNICALL Java_ai_rapids_cudf_Cuda_memcpy
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
