/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ai_rapids_bindings_cudf_CudfColumn */

#ifndef _Included_ai_rapids_bindings_cudf_CudfColumn
#define _Included_ai_rapids_bindings_cudf_CudfColumn
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ai_rapids_bindings_cudf_CudfColumn
 * Method:    allocate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ai_rapids_bindings_cudf_CudfColumn_allocate
  (JNIEnv *, jobject);

/*
 * Class:     ai_rapids_bindings_cudf_CudfColumn
 * Method:    cudfColumnView
 * Signature: (JJJII)V
 */
JNIEXPORT void JNICALL Java_ai_rapids_bindings_cudf_CudfColumn_cudfColumnView
  (JNIEnv *, jobject, jlong, jlong, jlong, jint, jint);

/*
 * Class:     ai_rapids_bindings_cudf_CudfColumn
 * Method:    cudfColumnViewAugmented
 * Signature: (JJJIIII)V
 */
JNIEXPORT void JNICALL Java_ai_rapids_bindings_cudf_CudfColumn_cudfColumnViewAugmented
  (JNIEnv *, jobject, jlong, jlong, jlong, jint, jint, jint, jint);

/*
 * Class:     ai_rapids_bindings_cudf_CudfColumn
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ai_rapids_bindings_cudf_CudfColumn_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_rapids_bindings_cudf_CudfColumn
 * Method:    getDataPtr
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_rapids_bindings_cudf_CudfColumn_getDataPtr
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_rapids_bindings_cudf_CudfColumn
 * Method:    getValidPtr
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ai_rapids_bindings_cudf_CudfColumn_getValidPtr
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_rapids_bindings_cudf_CudfColumn
 * Method:    getSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_rapids_bindings_cudf_CudfColumn_getSize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_rapids_bindings_cudf_CudfColumn
 * Method:    getDtype
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_rapids_bindings_cudf_CudfColumn_getDtype
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ai_rapids_bindings_cudf_CudfColumn
 * Method:    getNullCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ai_rapids_bindings_cudf_CudfColumn_getNullCount
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
